
import React, { useState } from 'react';
import { User, GalleryItem } from '../types';
import { Heart, Eye, Lock, Globe, Trash2, UploadCloud, XCircle } from 'lucide-react';

interface ProfileProps {
  currentUser: User;
  items: GalleryItem[];
  onItemClick: (item: GalleryItem) => void;
  onTogglePublish: (item: GalleryItem) => void;
  onDelete: (item: GalleryItem) => void;
}

const Profile: React.FC<ProfileProps> = ({ currentUser, items, onItemClick, onTogglePublish, onDelete }) => {
  const [activeTab, setActiveTab] = useState<'works' | 'history'>('works');

  // Filter items based on user
  const userItems = items.filter(item => item.authorId === currentUser.id);
  const publicWorks = userItems.filter(item => item.isPublic);
  // History includes everything generated by the user
  const historyWorks = [...userItems].sort((a, b) => b.timestamp - a.timestamp);

  // Determine what to show based on tab
  // 'works' tab shows public items only? Or maybe "My Gallery"?
  // Let's stick to standard convention: 
  // - Works = My Public Gallery
  // - History = All my generations (Private + Public)
  const displayItems = activeTab === 'works' ? publicWorks : historyWorks;

  const totalLikes = publicWorks.reduce((acc, item) => acc + item.likedBy.length, 0);
  const totalViews = publicWorks.reduce((acc, item) => acc + item.views, 0);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Profile Header */}
      <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-8 flex flex-col md:flex-row items-center gap-8 shadow-sm">
        <div className="w-24 h-24 bg-purple-100 rounded-full flex items-center justify-center text-3xl font-bold text-purple-600 overflow-hidden shadow-inner">
             {currentUser.avatar ? (
                 <img src={currentUser.avatar} alt="avatar" className="w-full h-full object-cover"/>
             ) : (
                 currentUser.username.charAt(0).toUpperCase()
             )}
        </div>
        
        <div className="flex-1 text-center md:text-left">
           <h1 className="text-3xl font-bold text-gray-900 mb-1">{currentUser.username}</h1>
           <p className="text-gray-500 mb-4">{currentUser.username}@miaoda.com</p>
           
           <div className="flex items-center justify-center md:justify-start gap-6">
               <div className="text-center p-3 bg-gray-50 rounded-lg min-w-[80px]">
                   <div className="text-xl font-bold text-gray-900">{publicWorks.length}</div>
                   <div className="text-xs text-gray-500 uppercase tracking-wide font-medium">Published</div>
               </div>
               
               <div className="text-center p-3 bg-gray-50 rounded-lg min-w-[80px]">
                   <div className="text-xl font-bold text-gray-900">{totalLikes}</div>
                   <div className="text-xs text-gray-500 uppercase tracking-wide font-medium">Likes</div>
               </div>
               
               <div className="text-center p-3 bg-gray-50 rounded-lg min-w-[80px]">
                   <div className="text-xl font-bold text-gray-900">{totalViews}</div>
                   <div className="text-xs text-gray-500 uppercase tracking-wide font-medium">Views</div>
               </div>
           </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white rounded-t-xl border border-gray-200 border-b-0 px-2 pt-2 flex gap-1 mb-0">
          <button
            onClick={() => setActiveTab('works')}
            className={`px-6 py-3 text-sm font-medium rounded-t-lg transition-colors flex items-center gap-2
              ${activeTab === 'works' ? 'bg-gray-50 text-purple-700 border-t border-x border-gray-200' : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'}`}
          >
              <Globe size={16} />
              Published Gallery ({publicWorks.length})
          </button>
          <button
            onClick={() => setActiveTab('history')}
            className={`px-6 py-3 text-sm font-medium rounded-t-lg transition-colors flex items-center gap-2
              ${activeTab === 'history' ? 'bg-gray-50 text-purple-700 border-t border-x border-gray-200' : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'}`}
          >
              <Lock size={16} />
              Generation History ({historyWorks.length})
          </button>
      </div>

      {/* Grid Content */}
      <div className="bg-gray-50 rounded-b-xl border border-gray-200 p-6 min-h-[400px]">
         <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {displayItems.map((item) => (
                <div key={item.id} className="bg-white rounded-xl border border-gray-200 overflow-hidden hover:shadow-md transition-shadow group flex flex-col relative">
                    <div 
                        className="relative aspect-square bg-gray-100 cursor-pointer overflow-hidden"
                        onClick={() => onItemClick(item)}
                    >
                         <img src={item.imageUrls[0]} alt={item.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                         
                         {/* Status Badge */}
                         <div className="absolute top-2 left-2 z-10">
                             {item.isPublic ? (
                                 <div className="bg-green-500/90 text-white p-1.5 rounded-md shadow-sm" title="Public">
                                     <Globe size={12} />
                                 </div>
                             ) : (
                                 <div className="bg-gray-500/90 text-white p-1.5 rounded-md shadow-sm" title="Private">
                                     <Lock size={12} />
                                 </div>
                             )}
                         </div>

                         <div className="absolute top-2 right-2 bg-black/40 text-white px-2 py-1 rounded-md text-xs font-semibold backdrop-blur-sm flex items-center gap-1 z-10">
                            <Heart size={12} className="fill-white" />
                            {item.likedBy.length}
                        </div>
                    </div>
                    
                    <div className="p-3 flex-1 flex flex-col">
                        <p className="text-sm text-gray-700 font-medium line-clamp-2 mb-2 h-10" title={item.prompt}>{item.prompt}</p>
                        
                        <div className="flex justify-between items-center text-xs text-gray-400 mt-auto mb-3">
                             <span>{item.date}</span>
                             <span className="flex items-center gap-1"><Eye size={12}/> {item.views}</span>
                        </div>

                        {/* Control Actions */}
                        <div className="pt-3 border-t border-gray-100 flex gap-2">
                            <button 
                                onClick={(e) => { e.stopPropagation(); onTogglePublish(item); }}
                                className={`flex-1 flex items-center justify-center gap-1 py-1.5 rounded text-xs font-medium transition-colors
                                  ${item.isPublic 
                                    ? 'bg-gray-100 text-gray-600 hover:bg-gray-200' 
                                    : 'bg-green-50 text-green-600 hover:bg-green-100'}`}
                            >
                                {item.isPublic ? <><XCircle size={12}/> Unpublish</> : <><UploadCloud size={12}/> Publish</>}
                            </button>
                            <button 
                                onClick={(e) => { e.stopPropagation(); onDelete(item); }}
                                className="px-3 py-1.5 rounded text-xs font-medium bg-red-50 text-red-500 hover:bg-red-100 transition-colors"
                                title="Delete"
                            >
                                <Trash2 size={12} />
                            </button>
                        </div>
                    </div>
                </div>
            ))}
         </div>
         
         {displayItems.length === 0 && (
             <div className="flex flex-col items-center justify-center h-64 text-gray-400">
                 <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4">
                    {activeTab === 'works' ? <Globe size={24} /> : <Lock size={24} />}
                 </div>
                 <div className="text-lg font-medium">No items found</div>
                 <p className="text-sm mt-2">
                     {activeTab === 'works' 
                       ? "You haven't published any works to the gallery yet." 
                       : "Your generation history is empty."}
                 </p>
             </div>
         )}
      </div>

    </div>
  );
};

export default Profile;
